### ISSUE TITLE
Mob of the Dead Plane Glitch

### ISSUE THREAD

**Issue by nsw-shadow** [Jbleezy/BO2-Reimagined#1]
Was playing with 2 players and we were unable to use the fuel cans on the plane. It kept saying that we needed additional parts despite it saying we had all the cans. Love what you're doing though with this mod and the BO1 one!

**Comment by Jbleezy** [comment]
Thanks for letting me know. This project was originally created on Redacted where only solo could be played, so there was an oversight due to the plane parts not being shared in coop.

This is now fixed. 8bfbf8017ac7dae8286e5f1e1e3502739607a8b8
