### ISSUE TITLE
Mistery Box

### ISSUE THREAD

**Issue by AdrikovXander** [Jbleezy/BO2-Reimagined#10]
The mystery box disappears when you pay for it and doesn't allow you to pay for perk machines
![20231026231345_1](https://github.com/Jbleezy/BO2-Reimagined/assets/149136619/100ca7eb-d03b-400f-9a65-d6f80d1f2b35)

**Comment by Jbleezy** [comment]
Do you have video of this occurring?

**Comment by AdrikovXander** [comment]
Yee, if u need: I have the purchased version of steam, link cuz github 10mb bruh

https://www.dropbox.com/scl/fi/wxw8zvwo88to28gzx9frp/Video-para-github.mp4?rlkey=ry8l881yqmrgyhp9zllmn81dm&dl=0

**Comment by Jbleezy** [comment]
This is fixed as of 9543bb8de3aa0c93b730eab2c570b3cc4a19c2da, please download the latest release.
