### ISSUE TITLE
[v1.3.4] Server script runtime error on 8 player Green Run game

### ISSUE THREAD

**Issue by VYRNACH** [Jbleezy/BO2-Reimagined#14]
![error2](https://github.com/Jbleezy/BO2-Reimagined/assets/19713025/7492ac33-0811-449f-89bc-a9df7194d0af)

**Comment by Jbleezy** [comment]
Do you have other scripts installed?

**Comment by THEYOUNGCOWBOY** [comment]
hello could I ask a favor
