### ISSUE TITLE
Bugs Burried Easter Egg (Maxis & Richtofen) 

### ISSUE THREAD

**Issue by Romdy02** [Jbleezy/BO2-Reimagined#15]
Hi Jbleezy, 

I sincerely hope you're well and salute your work on the latest mod update (Alpha 2.0.0 Alpha 3). I'm just opening this topic to point out a few things I've noticed (which may or may not be normal). Concerning the Maxis quest, is it normal to have to buy the bowie knife to cut the 5 plates that are in the mine because without it and using the regular knife, nothing happens when trying to cut them. As for the Richtofen quest, I've only come across the following bugs, and I've done this a dozen times: 

-Buy the bowie knife to cut the plates.
-During the infinite round stage, it's not possible to activate the delay bomb without having collected max ammo, because after throwing the bomb, the skin disappears and it's not possible to make it reappear.

If these are bugs for which I'm the only one to apologize, I apologize in advance.
Thank you very much,

**Comment by Jbleezy** [comment]
Both sides of the quest have always required Bowie Knife or Galvaknuckles.

I'm not sure what you are talking about for the 2nd part of the Richtofen quest.

**Comment by Romdy02** [comment]
For the infinite round step, when I throw the time bomb next to the guillotine, I can't activate it until I get max ammo. Envoyé de mon iPhoneLe 6 juin 2024 à 20:30, Jbleezy ***@***.***> a écrit :﻿
Both sides of the quest have always required Bowie Knife or Galvaknuckles.
I'm not sure what you are talking about for the 2nd part of the Richtofen quest.

**Comment by Jbleezy** [comment]
Do you have other scripts installed?

Does the Time Bomb work normally before that step?

**Comment by Romdy02** [comment]
Hi Dear,Regarding other installed scripts, I had to install your reimagined master mod, which is loaded by default when I launch the game, then I go to the mod menu to load 2.0.0 Alpha 3, and I launch the game. What I don't understand is that when I launch the time bomb, the detonator disappears and I can't make it reappear unless I get max ammo, I can send you a video if that helps. Thanks Le 7 juin 2024 à 02:10, Jbleezy ***@***.***> a écrit :﻿
Do you have other scripts installed?
Does the Time Bomb work normally before that step?

**Comment by Romdy02** [comment]
Hi dear,My problem is solved. The anomaly occurred because I used a menu mod, and by activating unlimited ammunition, it created the problem. I apologize for the inconvenience. Best regards, Rudy Envoyé de mon iPhoneLe 7 juin 2024 à 09:19, TORDJEMAN Rudy ***@***.***> a écrit :﻿Hi Dear,Regarding other installed scripts, I had to install your reimagined master mod, which is loaded by default when I launch the game, then I go to the mod menu to load 2.0.0 Alpha 3, and I launch the game. What I don't understand is that when I launch the time bomb, the detonator disappears and I can't make it reappear unless I get max ammo, I can send you a video if that helps. Thanks Le 7 juin 2024 à 02:10, Jbleezy ***@***.***> a écrit :﻿
Do you have other scripts installed?
Does the Time Bomb work normally before that step?

**Comment by Romdy02** [comment]
Hi Jbleezy,I have a problem on Buried with the bank. There is no money in the vault on the map, and when I store money, I find the account at 0 on a new game.  Is there anything specific I can do?  Thank you Envoyé de mon iPhoneLe 7 juin 2024 à 21:32, Jbleezy ***@***.***> a écrit :﻿
Closed #15 as completed.
