### ISSUE TITLE
[Question] Custom Installation

### ISSUE THREAD

**Issue by ElRafeta697** [Jbleezy/BO2-Reimagined#18]
There's a way or guide to install only some parts of the mod? I mean, I can modify the files and prepare my own installation in order to install Jetgun improves without install wallbuy changes, but there's a way to modify this from an UI or an easier way?

In case there isn't a way, have you planned to implement it? A kind of installation wizard or something.

**Comment by Jbleezy** [comment]
No, I make my projects with an all or nothing approach. I don't like having too many options.
