### ISSUE TITLE
Crashes when i try to load it on plutonium.

### ISSUE THREAD

**Issue by UnlockedHome** [Jbleezy/BO2-Reimagined#2]
any map i play, after it loads it crashes instantly. it also says in the console it failed to load stuff.

**Comment by Jbleezy** [comment]
You must compile the scripts first. I will make a compiled release once it is ready.

**Comment by TheFantasticLoki** [comment]
I already compiled it just now got it all working for the most part. How do I select the custom gamemode?

**Comment by Jbleezy** [comment]
Choose a Grief map.

`set ui_gametype_obj zgrief zsnr zrace zcontainment`

Remove any mode you don't want chosen.
