### ISSUE TITLE
Transparent Executioner on Origins

### ISSUE THREAD

**Issue by suarezsharp** [Jbleezy/BO2-Reimagined#22]
The Executioner is invisible on Origins - you see the shells floating where they should be inside the gun, and that's kinda funny actually

**Comment by suarezsharp** [comment]
![image](https://github.com/user-attachments/assets/7b358dee-c125-44e1-93bd-b391d675e332)

**Comment by Jbleezy** [comment]
What version is this? Is this a release or did you build yourself?

**Comment by Jbleezy** [comment]
Looks like it was more than just the Executioner affected. These 2 commits should fix it.
720449b
d2f0e89
