### ISSUE TITLE
Weird compiling errors

### ISSUE THREAD

**Issue by SwordSWD** [Jbleezy/BO2-Reimagined#6]
![image](https://user-images.githubusercontent.com/62721069/230505072-de3665f0-b960-4695-b5b6-ad1deb01b6b7.png)

**Comment by Jbleezy** [comment]
You renamed the files, they are not going to work properly unless you modify the folder names in the scripts also.

**Comment by SwordSWD** [comment]
![image](https://user-images.githubusercontent.com/62721069/230508525-449a4717-889c-4c71-9e07-977b825c7fab.png)
Well this is with the file i yoinked from the repository.

**Comment by SwordSWD** [comment]
Unless it's supposed to be in like `scripts/zm/zm_buried/zm_buried_reimagined.gsc`

**Comment by Jbleezy** [comment]
You're not really going to be able to yoink specific files, a lot of them are interconnected.

**Comment by SwordSWD** [comment]
> You're not really going to be able to yoink specific files, a lot of them are interconnected.
Ah. So what should i do

**Comment by SwordSWD** [comment]
This is on a server btw

**Comment by Jbleezy** [comment]
Simply copy the whole scripts folder into `Plutonium\storage\t6`

**Comment by SwordSWD** [comment]
Alright thanks
