### ISSUE TITLE
_hash_2ECA0C0E variable not found?

### ISSUE THREAD

**Issue by Flickersir** [Jbleezy/BO2-Reimagined#9]
![image](https://github.com/Jbleezy/BO2-Reimagined/assets/133500892/560c2c2f-abd2-41ef-82c9-b59e180e3e7a)
yea nothing too much to explain, this is just an error I get.

**Comment by Jbleezy** [comment]
I will release an update after Plutonium's next update, as there are also other issues causing the mod not to work on the current Plutonium version.
